/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. */
/* Stub bodies for every Win16 import + interrupt handler, so the   */
/* lifted engine links. Each logs once (with -DCATZ_TRACE_WIN16) and */
/* returns ax=0. Replace with real behavior hottest-API-first.       */
#include "runtime_api.h"
#include <stdio.h>

#ifdef CATZ_TRACE_WIN16
#define WIN16_LOG(n) do { static int _seen; if (!_seen) { _seen = 1; \
    fprintf(stderr, "[win16] %s (stub)\n", (n)); } } while (0)
#else
#define WIN16_LOG(n) ((void)0)
#endif
/* Loud warning the first time an unknown-purge stub runs: its stack
 * cleanup is a guess and may corrupt. Add it to PURGE in win16.py. */
#define WIN16_UNKNOWN(n) do { static int _w; if (!_w) { _w = 1; \
    fprintf(stderr, "[win16] *** %s: unknown stack purge (guessed 0)\n", (n)); \
    } } while (0)

void int_handler(CPU *cpu, int int_num) {
    (void)cpu; WIN16_LOG("int_handler");
    fprintf(stderr, "[int] unhandled INT 0x%02X\n", int_num);
}

/* ===== COMMDLG ===== */
void COMMDLG_CHOOSECOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("CHOOSECOLOR"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("CHOOSECOLOR"); }
void COMMDLG_GETSAVEFILENAME(CPU *cpu) { (void)cpu; WIN16_LOG("GETSAVEFILENAME"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETSAVEFILENAME"); }

/* ===== CTL3DV2 ===== */
void CTL3DV2_CTL3DCOLORCHANGE(CPU *cpu) { (void)cpu; WIN16_LOG("CTL3DCOLORCHANGE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("CTL3DCOLORCHANGE"); }
void CTL3DV2_CTL3DUNREGISTER(CPU *cpu) { (void)cpu; WIN16_LOG("CTL3DUNREGISTER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("CTL3DUNREGISTER"); }

/* ===== GDI ===== */
void GDI_BITBLT(CPU *cpu) { (void)cpu; WIN16_LOG("BITBLT"); cpu->ax = 0; cpu->sp += 4 + 20; }
void GDI_CREATEDIBITMAP(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIBITMAP"); cpu->ax = 0; cpu->sp += 4 + 20; }
void GDI_CREATEFONTINDIRECT(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEFONTINDIRECT"); cpu->ax = 0; cpu->sp += 4 + 4; }
void GDI_ELLIPSE(CPU *cpu) { (void)cpu; WIN16_LOG("ELLIPSE"); cpu->ax = 0; cpu->sp += 4 + 10; }
void GDI_GETDIBITS(CPU *cpu) { (void)cpu; WIN16_LOG("GETDIBITS"); cpu->ax = 0; cpu->sp += 4 + 18; }
void GDI_GETOBJECT(CPU *cpu) { (void)cpu; WIN16_LOG("GETOBJECT"); cpu->ax = 0; cpu->sp += 4 + 8; }
void GDI_GETTEXTEXTENT(CPU *cpu) { (void)cpu; WIN16_LOG("GETTEXTEXTENT"); cpu->ax = 0; cpu->sp += 4 + 8; }
void GDI_LINETO(CPU *cpu) { (void)cpu; WIN16_LOG("LINETO"); cpu->ax = 0; cpu->sp += 4 + 6; }
void GDI_MOVETO(CPU *cpu) { (void)cpu; WIN16_LOG("MOVETO"); cpu->ax = 0; cpu->sp += 4 + 6; }
void GDI_POLYGON(CPU *cpu) { (void)cpu; WIN16_LOG("POLYGON"); cpu->ax = 0; cpu->sp += 4 + 8; }
void GDI_RECTANGLE(CPU *cpu) { (void)cpu; WIN16_LOG("RECTANGLE"); cpu->ax = 0; cpu->sp += 4 + 10; }
void GDI_SETBKCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETBKCOLOR"); cpu->ax = 0; cpu->sp += 4 + 6; }
void GDI_SETBKMODE(CPU *cpu) { (void)cpu; WIN16_LOG("SETBKMODE"); cpu->ax = 0; cpu->sp += 4 + 4; }
void GDI_SETDIBITSTODEVICE(CPU *cpu) { (void)cpu; WIN16_LOG("SETDIBITSTODEVICE"); cpu->ax = 0; cpu->sp += 4 + 28; }
void GDI_SETTEXTCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETTEXTCOLOR"); cpu->ax = 0; cpu->sp += 4 + 6; }
void GDI_SETVIEWPORTORGEX(CPU *cpu) { (void)cpu; WIN16_LOG("SETVIEWPORTORGEX"); cpu->ax = 0; cpu->sp += 4 + 10; }
void GDI_STRETCHBLT(CPU *cpu) { (void)cpu; WIN16_LOG("STRETCHBLT"); cpu->ax = 0; cpu->sp += 4 + 24; }
void GDI_STRETCHDIBITS(CPU *cpu) { (void)cpu; WIN16_LOG("STRETCHDIBITS"); cpu->ax = 0; cpu->sp += 4 + 32; }

/* ===== KERNEL ===== */
void KERNEL_GETPROFILEINT(CPU *cpu) { (void)cpu; WIN16_LOG("GETPROFILEINT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETPROFILEINT"); }
void KERNEL_GETSYSTEMDIRECTORY(CPU *cpu) { (void)cpu; WIN16_LOG("GETSYSTEMDIRECTORY"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETSYSTEMDIRECTORY"); }
void KERNEL_GLOBALDOSALLOC(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALDOSALLOC"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GLOBALDOSALLOC"); }
void KERNEL_GLOBALDOSFREE(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALDOSFREE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GLOBALDOSFREE"); }
void KERNEL_WINEXEC(CPU *cpu) { (void)cpu; WIN16_LOG("WINEXEC"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("WINEXEC"); }
void KERNEL_WRITEPRIVATEPROFILESTRING(CPU *cpu) { (void)cpu; WIN16_LOG("WRITEPRIVATEPROFILESTRING"); cpu->ax = 0; cpu->sp += 4 + 16; }
void KERNEL_WRITEPROFILESTRING(CPU *cpu) { (void)cpu; WIN16_LOG("WRITEPROFILESTRING"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("WRITEPROFILESTRING"); }
void KERNEL__HREAD(CPU *cpu) { (void)cpu; WIN16_LOG("_HREAD"); cpu->ax = 0; cpu->sp += 4 + 10; }
void KERNEL___AHSHIFT(CPU *cpu) { (void)cpu; WIN16_LOG("__AHSHIFT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("__AHSHIFT"); }

/* ===== MMSYSTEM ===== */
void MMSYSTEM_SNDPLAYSOUND(CPU *cpu) { (void)cpu; WIN16_LOG("SNDPLAYSOUND"); cpu->ax = 0; cpu->sp += 4 + 6; }
void MMSYSTEM_TIMEGETDEVCAPS(CPU *cpu) { (void)cpu; WIN16_LOG("TIMEGETDEVCAPS"); cpu->ax = 0; cpu->sp += 4 + 6; }

/* ===== SOSLIB03 ===== */
void SOSLIB03_SOSDIGIACQUIREDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIACQUIREDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIACQUIREDRIVER"); }
void SOSLIB03_SOSDIGIDETECTFINDFIRST(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTFINDFIRST"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIDETECTFINDFIRST"); }
void SOSLIB03_SOSDIGIDETECTINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTINIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIDETECTINIT"); }
void SOSLIB03_SOSDIGIDETECTUNINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTUNINIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIDETECTUNINIT"); }
void SOSLIB03_SOSDIGIINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIINITDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIINITDRIVER"); }
void SOSLIB03_SOSDIGIINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIINITSYSTEM"); }
void SOSLIB03_SOSDIGIRELEASEDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIRELEASEDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIRELEASEDRIVER"); }
void SOSLIB03_SOSDIGISAMPLEDONE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISAMPLEDONE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISAMPLEDONE"); }
void SOSLIB03_SOSDIGISAMPLESPLAYING(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISAMPLESPLAYING"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISAMPLESPLAYING"); }
void SOSLIB03_SOSDIGISETACTIVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISETACTIVEWINDOW"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISETACTIVEWINDOW"); }
void SOSLIB03_SOSDIGISTARTSAMPLE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTARTSAMPLE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTARTSAMPLE"); }
void SOSLIB03_SOSDIGISTOPALLSAMPLES(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTOPALLSAMPLES"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTOPALLSAMPLES"); }
void SOSLIB03_SOSDIGISTREAMACQUIRE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMACQUIRE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMACQUIRE"); }
void SOSLIB03_SOSDIGISTREAMADDBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMADDBUFFER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMADDBUFFER"); }
void SOSLIB03_SOSDIGISTREAMPREPAREBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMPREPAREBUFFER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMPREPAREBUFFER"); }
void SOSLIB03_SOSDIGISTREAMRELEASE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMRELEASE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMRELEASE"); }
void SOSLIB03_SOSDIGISTREAMSTART(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMSTART"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMSTART"); }
void SOSLIB03_SOSDIGISTREAMSTOP(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMSTOP"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMSTOP"); }
void SOSLIB03_SOSDIGISTREAMUNPREPAREBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMUNPREPAREBUFFER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGISTREAMUNPREPAREBUFFER"); }
void SOSLIB03_SOSDIGIUNINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUNINITDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIUNINITDRIVER"); }
void SOSLIB03_SOSDIGIUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUNINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIUNINITSYSTEM"); }
void SOSLIB03_SOSDIGIUSERSERVICE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUSERSERVICE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSDIGIUSERSERVICE"); }
void SOSLIB03_SOSGETERRORSTRING(CPU *cpu) { (void)cpu; WIN16_LOG("SOSGETERRORSTRING"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSGETERRORSTRING"); }
void SOSLIB03_SOSMIDIDETECTFINDFIRST(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTFINDFIRST"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIDETECTFINDFIRST"); }
void SOSLIB03_SOSMIDIDETECTFINDNEXT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTFINDNEXT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIDETECTFINDNEXT"); }
void SOSLIB03_SOSMIDIDETECTINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTINIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIDETECTINIT"); }
void SOSLIB03_SOSMIDIDETECTUNINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTUNINIT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIDETECTUNINIT"); }
void SOSLIB03_SOSMIDIINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIINITDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIINITDRIVER"); }
void SOSLIB03_SOSMIDIINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIINITSYSTEM"); }
void SOSLIB03_SOSMIDIRESETDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIRESETDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIRESETDRIVER"); }
void SOSLIB03_SOSMIDISETACTIVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISETACTIVEWINDOW"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDISETACTIVEWINDOW"); }
void SOSLIB03_SOSMIDISETINSDATA(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISETINSDATA"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDISETINSDATA"); }
void SOSLIB03_SOSMIDISTOPALLSONGS(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISTOPALLSONGS"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDISTOPALLSONGS"); }
void SOSLIB03_SOSMIDIUNINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIUNINITDRIVER"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIUNINITDRIVER"); }
void SOSLIB03_SOSMIDIUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIUNINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSMIDIUNINITSYSTEM"); }
void SOSLIB03_SOSTIMERINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSTIMERINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSTIMERINITSYSTEM"); }
void SOSLIB03_SOSTIMERUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSTIMERUNINITSYSTEM"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SOSTIMERUNINITSYSTEM"); }

/* ===== TOOLHELP ===== */
void TOOLHELP_TIMERCOUNT(CPU *cpu) { (void)cpu; WIN16_LOG("TIMERCOUNT"); cpu->ax = 0; cpu->sp += 4 + 4; }

/* ===== USER ===== */
void USER_BRINGWINDOWTOTOP(CPU *cpu) { (void)cpu; WIN16_LOG("BRINGWINDOWTOTOP"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("BRINGWINDOWTOTOP"); }
void USER_CHECKDLGBUTTON(CPU *cpu) { (void)cpu; WIN16_LOG("CHECKDLGBUTTON"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("CHECKDLGBUTTON"); }
void USER_CHECKMENUITEM(CPU *cpu) { (void)cpu; WIN16_LOG("CHECKMENUITEM"); cpu->ax = 0; cpu->sp += 4 + 6; }
void USER_CLIENTTOSCREEN(CPU *cpu) { (void)cpu; WIN16_LOG("CLIENTTOSCREEN"); cpu->ax = 0; cpu->sp += 4 + 6; }
void USER_CLIPCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("CLIPCURSOR"); cpu->ax = 0; cpu->sp += 4 + 4; }
void USER_CREATEDIALOG(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIALOG"); cpu->ax = 0; cpu->sp += 4 + 12; }
void USER_CREATEDIALOGPARAM(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIALOGPARAM"); cpu->ax = 0; cpu->sp += 4 + 16; }
void USER_DEFWINDOWPROC(CPU *cpu) { (void)cpu; WIN16_LOG("DEFWINDOWPROC"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_DESTROYICON(CPU *cpu) { (void)cpu; WIN16_LOG("DESTROYICON"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("DESTROYICON"); }
void USER_DIALOGBOX(CPU *cpu) { (void)cpu; WIN16_LOG("DIALOGBOX"); cpu->ax = 0; cpu->sp += 4 + 12; }
void USER_DRAWTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("DRAWTEXT"); cpu->ax = 0; cpu->sp += 4 + 14; }
void USER_ENABLEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("ENABLEWINDOW"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("ENABLEWINDOW"); }
void USER_ENUMWINDOWS(CPU *cpu) { (void)cpu; WIN16_LOG("ENUMWINDOWS"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_FRAMERECT(CPU *cpu) { (void)cpu; WIN16_LOG("FRAMERECT"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_GETACTIVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("GETACTIVEWINDOW"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETACTIVEWINDOW"); }
void USER_GETASYNCKEYSTATE(CPU *cpu) { (void)cpu; WIN16_LOG("GETASYNCKEYSTATE"); cpu->ax = 0; cpu->sp += 4 + 2; }
void USER_GETCLASSNAME(CPU *cpu) { (void)cpu; WIN16_LOG("GETCLASSNAME"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETCLASSNAME"); }
void USER_GETCURSORPOS(CPU *cpu) { (void)cpu; WIN16_LOG("GETCURSORPOS"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETCURSORPOS"); }
void USER_GETDESKTOPWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("GETDESKTOPWINDOW"); cpu->ax = 0; cpu->sp += 4 + 0; }
void USER_GETDLGITEMINT(CPU *cpu) { (void)cpu; WIN16_LOG("GETDLGITEMINT"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_GETFOCUS(CPU *cpu) { (void)cpu; WIN16_LOG("GETFOCUS"); cpu->ax = 0; cpu->sp += 4 + 0; }
void USER_GETSYSCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("GETSYSCOLOR"); cpu->ax = 0; cpu->sp += 4 + 2; }
void USER_GETWINDOWLONG(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINDOWLONG"); cpu->ax = 0; cpu->sp += 4 + 4; }
void USER_GETWINDOWPLACEMENT(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINDOWPLACEMENT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETWINDOWPLACEMENT"); }
void USER_GETWINDOWWORD(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINDOWWORD"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("GETWINDOWWORD"); }
void USER_INFLATERECT(CPU *cpu) { (void)cpu; WIN16_LOG("INFLATERECT"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("INFLATERECT"); }
void USER_ISDIALOGMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("ISDIALOGMESSAGE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("ISDIALOGMESSAGE"); }
void USER_ISDLGBUTTONCHECKED(CPU *cpu) { (void)cpu; WIN16_LOG("ISDLGBUTTONCHECKED"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("ISDLGBUTTONCHECKED"); }
void USER_ISICONIC(CPU *cpu) { (void)cpu; WIN16_LOG("ISICONIC"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("ISICONIC"); }
void USER_ISWINDOWVISIBLE(CPU *cpu) { (void)cpu; WIN16_LOG("ISWINDOWVISIBLE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("ISWINDOWVISIBLE"); }
void USER_LOADCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("LOADCURSOR"); cpu->ax = 0; cpu->sp += 4 + 6; }
void USER_MOVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("MOVEWINDOW"); cpu->ax = 0; cpu->sp += 4 + 12; }
void USER_OFFSETRECT(CPU *cpu) { (void)cpu; WIN16_LOG("OFFSETRECT"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_REDRAWWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("REDRAWWINDOW"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_RELEASECAPTURE(CPU *cpu) { (void)cpu; WIN16_LOG("RELEASECAPTURE"); cpu->ax = 0; cpu->sp += 4 + 0; }
void USER_SENDDLGITEMMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("SENDDLGITEMMESSAGE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SENDDLGITEMMESSAGE"); }
void USER_SENDMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("SENDMESSAGE"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_SETCAPTURE(CPU *cpu) { (void)cpu; WIN16_LOG("SETCAPTURE"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SETCAPTURE"); }
void USER_SETCLASSWORD(CPU *cpu) { (void)cpu; WIN16_LOG("SETCLASSWORD"); cpu->ax = 0; cpu->sp += 4 + 6; }
void USER_SETCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETCURSOR"); cpu->ax = 0; cpu->sp += 4 + 2; }
void USER_SETCURSORPOS(CPU *cpu) { (void)cpu; WIN16_LOG("SETCURSORPOS"); cpu->ax = 0; cpu->sp += 4 + 4; }
void USER_SETDLGITEMINT(CPU *cpu) { (void)cpu; WIN16_LOG("SETDLGITEMINT"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_SETSCROLLPOS(CPU *cpu) { (void)cpu; WIN16_LOG("SETSCROLLPOS"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_SETSCROLLRANGE(CPU *cpu) { (void)cpu; WIN16_LOG("SETSCROLLRANGE"); cpu->ax = 0; cpu->sp += 4 + 10; }
void USER_SETWINDOWLONG(CPU *cpu) { (void)cpu; WIN16_LOG("SETWINDOWLONG"); cpu->ax = 0; cpu->sp += 4 + 8; }
void USER_SETWINDOWPOS(CPU *cpu) { (void)cpu; WIN16_LOG("SETWINDOWPOS"); cpu->ax = 0; cpu->sp += 4 + 14; }
void USER_SETWINDOWTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("SETWINDOWTEXT"); cpu->ax = 0; cpu->sp += 4 + 6; }
void USER_SWAPMOUSEBUTTON(CPU *cpu) { (void)cpu; WIN16_LOG("SWAPMOUSEBUTTON"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SWAPMOUSEBUTTON"); }
void USER_SYSTEMPARAMETERSINFO(CPU *cpu) { (void)cpu; WIN16_LOG("SYSTEMPARAMETERSINFO"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("SYSTEMPARAMETERSINFO"); }
void USER_WINHELP(CPU *cpu) { (void)cpu; WIN16_LOG("WINHELP"); cpu->ax = 0; cpu->sp += 4; WIN16_UNKNOWN("WINHELP"); }

/* ===== WIN87EM ===== */
void WIN87EM___FPMATH(CPU *cpu) { (void)cpu; WIN16_LOG("__FPMATH"); cpu->ax = 0; cpu->sp += 4 + 0; }

