/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. */
/* Stub bodies for every Win16 import + interrupt handler, so the   */
/* lifted engine links. Each logs once (with -DCATZ_TRACE_WIN16) and */
/* returns ax=0. Replace with real behavior hottest-API-first.       */
#include "runtime_api.h"
#include <stdio.h>

#ifdef CATZ_TRACE_WIN16
#define WIN16_LOG(n) do { static int _seen; if (!_seen) { _seen = 1; \
    fprintf(stderr, "[win16] %s (stub)\n", (n)); } } while (0)
#else
#define WIN16_LOG(n) ((void)0)
#endif

void int_handler(CPU *cpu, int int_num) {
    (void)cpu; WIN16_LOG("int_handler");
    fprintf(stderr, "[int] unhandled INT 0x%02X\n", int_num);
}
void dos_int21(CPU *cpu) { (void)cpu; WIN16_LOG("dos_int21"); }

/* ===== GDI ===== */
void GDI_BITBLT(CPU *cpu) { (void)cpu; WIN16_LOG("BITBLT"); cpu->ax = 0; }
void GDI_CREATECOMPATIBLEBITMAP(CPU *cpu) { (void)cpu; WIN16_LOG("CREATECOMPATIBLEBITMAP"); cpu->ax = 0; }
void GDI_CREATECOMPATIBLEDC(CPU *cpu) { (void)cpu; WIN16_LOG("CREATECOMPATIBLEDC"); cpu->ax = 0; }
void GDI_CREATEDIBITMAP(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIBITMAP"); cpu->ax = 0; }
void GDI_CREATEFONTINDIRECT(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEFONTINDIRECT"); cpu->ax = 0; }
void GDI_CREATEIC(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEIC"); cpu->ax = 0; }
void GDI_CREATEPALETTE(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEPALETTE"); cpu->ax = 0; }
void GDI_CREATEPEN(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEPEN"); cpu->ax = 0; }
void GDI_CREATESOLIDBRUSH(CPU *cpu) { (void)cpu; WIN16_LOG("CREATESOLIDBRUSH"); cpu->ax = 0; }
void GDI_DELETEDC(CPU *cpu) { (void)cpu; WIN16_LOG("DELETEDC"); cpu->ax = 0; }
void GDI_DELETEOBJECT(CPU *cpu) { (void)cpu; WIN16_LOG("DELETEOBJECT"); cpu->ax = 0; }
void GDI_ELLIPSE(CPU *cpu) { (void)cpu; WIN16_LOG("ELLIPSE"); cpu->ax = 0; }
void GDI_GETDEVICECAPS(CPU *cpu) { (void)cpu; WIN16_LOG("GETDEVICECAPS"); cpu->ax = 0; }
void GDI_GETDIBITS(CPU *cpu) { (void)cpu; WIN16_LOG("GETDIBITS"); cpu->ax = 0; }
void GDI_GETOBJECT(CPU *cpu) { (void)cpu; WIN16_LOG("GETOBJECT"); cpu->ax = 0; }
void GDI_GETSTOCKOBJECT(CPU *cpu) { (void)cpu; WIN16_LOG("GETSTOCKOBJECT"); cpu->ax = 0; }
void GDI_GETSYSTEMPALETTEENTRIES(CPU *cpu) { (void)cpu; WIN16_LOG("GETSYSTEMPALETTEENTRIES"); cpu->ax = 0; }
void GDI_GETSYSTEMPALETTEUSE(CPU *cpu) { (void)cpu; WIN16_LOG("GETSYSTEMPALETTEUSE"); cpu->ax = 0; }
void GDI_GETTEXTEXTENT(CPU *cpu) { (void)cpu; WIN16_LOG("GETTEXTEXTENT"); cpu->ax = 0; }
void GDI_LINETO(CPU *cpu) { (void)cpu; WIN16_LOG("LINETO"); cpu->ax = 0; }
void GDI_MOVETO(CPU *cpu) { (void)cpu; WIN16_LOG("MOVETO"); cpu->ax = 0; }
void GDI_PATBLT(CPU *cpu) { (void)cpu; WIN16_LOG("PATBLT"); cpu->ax = 0; }
void GDI_POLYGON(CPU *cpu) { (void)cpu; WIN16_LOG("POLYGON"); cpu->ax = 0; }
void GDI_RECTANGLE(CPU *cpu) { (void)cpu; WIN16_LOG("RECTANGLE"); cpu->ax = 0; }
void GDI_SELECTOBJECT(CPU *cpu) { (void)cpu; WIN16_LOG("SELECTOBJECT"); cpu->ax = 0; }
void GDI_SETBKCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETBKCOLOR"); cpu->ax = 0; }
void GDI_SETBKMODE(CPU *cpu) { (void)cpu; WIN16_LOG("SETBKMODE"); cpu->ax = 0; }
void GDI_SETDIBITSTODEVICE(CPU *cpu) { (void)cpu; WIN16_LOG("SETDIBITSTODEVICE"); cpu->ax = 0; }
void GDI_SETTEXTCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETTEXTCOLOR"); cpu->ax = 0; }
void GDI_SETVIEWPORTORGEX(CPU *cpu) { (void)cpu; WIN16_LOG("SETVIEWPORTORGEX"); cpu->ax = 0; }
void GDI_STRETCHBLT(CPU *cpu) { (void)cpu; WIN16_LOG("STRETCHBLT"); cpu->ax = 0; }
void GDI_STRETCHDIBITS(CPU *cpu) { (void)cpu; WIN16_LOG("STRETCHDIBITS"); cpu->ax = 0; }

/* ===== KERNEL ===== */
void KERNEL_FINDRESOURCE(CPU *cpu) { (void)cpu; WIN16_LOG("FINDRESOURCE"); cpu->ax = 0; }
void KERNEL_FREELIBRARY(CPU *cpu) { (void)cpu; WIN16_LOG("FREELIBRARY"); cpu->ax = 0; }
void KERNEL_FREERESOURCE(CPU *cpu) { (void)cpu; WIN16_LOG("FREERESOURCE"); cpu->ax = 0; }
void KERNEL_GETCURRENTTASK(CPU *cpu) { (void)cpu; WIN16_LOG("GETCURRENTTASK"); cpu->ax = 0; }
void KERNEL_GETMODULEFILENAME(CPU *cpu) { (void)cpu; WIN16_LOG("GETMODULEFILENAME"); cpu->ax = 0; }
void KERNEL_GETMODULEUSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("GETMODULEUSAGE"); cpu->ax = 0; }
void KERNEL_GETPRIVATEPROFILEINT(CPU *cpu) { (void)cpu; WIN16_LOG("GETPRIVATEPROFILEINT"); cpu->ax = 0; }
void KERNEL_GETPRIVATEPROFILESTRING(CPU *cpu) { (void)cpu; WIN16_LOG("GETPRIVATEPROFILESTRING"); cpu->ax = 0; }
void KERNEL_GETVERSION(CPU *cpu) { (void)cpu; WIN16_LOG("GETVERSION"); cpu->ax = 0; }
void KERNEL_GETWINFLAGS(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINFLAGS"); cpu->ax = 0; }
void KERNEL_GLOBALALLOC(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALALLOC"); cpu->ax = 0; }
void KERNEL_GLOBALFREE(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALFREE"); cpu->ax = 0; }
void KERNEL_GLOBALHANDLE(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALHANDLE"); cpu->ax = 0; }
void KERNEL_GLOBALLOCK(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALLOCK"); cpu->ax = 0; }
void KERNEL_GLOBALREALLOC(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALREALLOC"); cpu->ax = 0; }
void KERNEL_GLOBALSIZE(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALSIZE"); cpu->ax = 0; }
void KERNEL_GLOBALUNLOCK(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALUNLOCK"); cpu->ax = 0; }
void KERNEL_LOADLIBRARY(CPU *cpu) { (void)cpu; WIN16_LOG("LOADLIBRARY"); cpu->ax = 0; }
void KERNEL_LOADRESOURCE(CPU *cpu) { (void)cpu; WIN16_LOG("LOADRESOURCE"); cpu->ax = 0; }
void KERNEL_LOCALINIT(CPU *cpu) { (void)cpu; WIN16_LOG("LOCALINIT"); cpu->ax = 0; }
void KERNEL_LOCKRESOURCE(CPU *cpu) { (void)cpu; WIN16_LOG("LOCKRESOURCE"); cpu->ax = 0; }
void KERNEL_OPENFILE(CPU *cpu) { (void)cpu; WIN16_LOG("OPENFILE"); cpu->ax = 0; }
void KERNEL_OUTPUTDEBUGSTRING(CPU *cpu) { (void)cpu; WIN16_LOG("OUTPUTDEBUGSTRING"); cpu->ax = 0; }
void KERNEL_SIZEOFRESOURCE(CPU *cpu) { (void)cpu; WIN16_LOG("SIZEOFRESOURCE"); cpu->ax = 0; }
void KERNEL_WRITEPRIVATEPROFILESTRING(CPU *cpu) { (void)cpu; WIN16_LOG("WRITEPRIVATEPROFILESTRING"); cpu->ax = 0; }
void KERNEL__HREAD(CPU *cpu) { (void)cpu; WIN16_LOG("_HREAD"); cpu->ax = 0; }
void KERNEL__LCLOSE(CPU *cpu) { (void)cpu; WIN16_LOG("_LCLOSE"); cpu->ax = 0; }
void KERNEL__LLSEEK(CPU *cpu) { (void)cpu; WIN16_LOG("_LLSEEK"); cpu->ax = 0; }
void KERNEL__LOPEN(CPU *cpu) { (void)cpu; WIN16_LOG("_LOPEN"); cpu->ax = 0; }
void KERNEL__LREAD(CPU *cpu) { (void)cpu; WIN16_LOG("_LREAD"); cpu->ax = 0; }
void KERNEL__LWRITE(CPU *cpu) { (void)cpu; WIN16_LOG("_LWRITE"); cpu->ax = 0; }
void KERNEL___AHSHIFT(CPU *cpu) { (void)cpu; WIN16_LOG("__AHSHIFT"); cpu->ax = 0; }

/* ===== MMSYSTEM ===== */
void MMSYSTEM_SNDPLAYSOUND(CPU *cpu) { (void)cpu; WIN16_LOG("SNDPLAYSOUND"); cpu->ax = 0; }
void MMSYSTEM_TIMEGETDEVCAPS(CPU *cpu) { (void)cpu; WIN16_LOG("TIMEGETDEVCAPS"); cpu->ax = 0; }
void MMSYSTEM_TIMEGETTIME(CPU *cpu) { (void)cpu; WIN16_LOG("TIMEGETTIME"); cpu->ax = 0; }

/* ===== SOSLIB03 ===== */
void SOSLIB03_SOSDIGIACQUIREDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIACQUIREDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIDETECTFINDFIRST(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTFINDFIRST"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIDETECTINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTINIT"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIDETECTUNINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIDETECTUNINIT"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIINITDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIINITSYSTEM"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIRELEASEDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIRELEASEDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISAMPLEDONE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISAMPLEDONE"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISAMPLESPLAYING(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISAMPLESPLAYING"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISETACTIVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISETACTIVEWINDOW"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTARTSAMPLE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTARTSAMPLE"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTOPALLSAMPLES(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTOPALLSAMPLES"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMACQUIRE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMACQUIRE"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMADDBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMADDBUFFER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMPREPAREBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMPREPAREBUFFER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMRELEASE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMRELEASE"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMSTART(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMSTART"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMSTOP(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMSTOP"); cpu->ax = 0; }
void SOSLIB03_SOSDIGISTREAMUNPREPAREBUFFER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGISTREAMUNPREPAREBUFFER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIUNINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUNINITDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUNINITSYSTEM"); cpu->ax = 0; }
void SOSLIB03_SOSDIGIUSERSERVICE(CPU *cpu) { (void)cpu; WIN16_LOG("SOSDIGIUSERSERVICE"); cpu->ax = 0; }
void SOSLIB03_SOSGETERRORSTRING(CPU *cpu) { (void)cpu; WIN16_LOG("SOSGETERRORSTRING"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIDETECTFINDFIRST(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTFINDFIRST"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIDETECTFINDNEXT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTFINDNEXT"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIDETECTINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTINIT"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIDETECTUNINIT(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIDETECTUNINIT"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIINITDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIINITSYSTEM"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIRESETDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIRESETDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSMIDISETACTIVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISETACTIVEWINDOW"); cpu->ax = 0; }
void SOSLIB03_SOSMIDISETINSDATA(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISETINSDATA"); cpu->ax = 0; }
void SOSLIB03_SOSMIDISTOPALLSONGS(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDISTOPALLSONGS"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIUNINITDRIVER(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIUNINITDRIVER"); cpu->ax = 0; }
void SOSLIB03_SOSMIDIUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSMIDIUNINITSYSTEM"); cpu->ax = 0; }
void SOSLIB03_SOSTIMERINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSTIMERINITSYSTEM"); cpu->ax = 0; }
void SOSLIB03_SOSTIMERUNINITSYSTEM(CPU *cpu) { (void)cpu; WIN16_LOG("SOSTIMERUNINITSYSTEM"); cpu->ax = 0; }

/* ===== TOOLHELP ===== */
void TOOLHELP_GLOBALENTRYHANDLE(CPU *cpu) { (void)cpu; WIN16_LOG("GLOBALENTRYHANDLE"); cpu->ax = 0; }
void TOOLHELP_TIMERCOUNT(CPU *cpu) { (void)cpu; WIN16_LOG("TIMERCOUNT"); cpu->ax = 0; }

/* ===== USER ===== */
void USER_CLIENTTOSCREEN(CPU *cpu) { (void)cpu; WIN16_LOG("CLIENTTOSCREEN"); cpu->ax = 0; }
void USER_CLIPCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("CLIPCURSOR"); cpu->ax = 0; }
void USER_CREATEDIALOG(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIALOG"); cpu->ax = 0; }
void USER_CREATEDIALOGPARAM(CPU *cpu) { (void)cpu; WIN16_LOG("CREATEDIALOGPARAM"); cpu->ax = 0; }
void USER_DESTROYWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("DESTROYWINDOW"); cpu->ax = 0; }
void USER_DIALOGBOX(CPU *cpu) { (void)cpu; WIN16_LOG("DIALOGBOX"); cpu->ax = 0; }
void USER_DISPATCHMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("DISPATCHMESSAGE"); cpu->ax = 0; }
void USER_DRAWTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("DRAWTEXT"); cpu->ax = 0; }
void USER_ENDDIALOG(CPU *cpu) { (void)cpu; WIN16_LOG("ENDDIALOG"); cpu->ax = 0; }
void USER_ENUMTASKWINDOWS(CPU *cpu) { (void)cpu; WIN16_LOG("ENUMTASKWINDOWS"); cpu->ax = 0; }
void USER_ENUMWINDOWS(CPU *cpu) { (void)cpu; WIN16_LOG("ENUMWINDOWS"); cpu->ax = 0; }
void USER_FRAMERECT(CPU *cpu) { (void)cpu; WIN16_LOG("FRAMERECT"); cpu->ax = 0; }
void USER_GETASYNCKEYSTATE(CPU *cpu) { (void)cpu; WIN16_LOG("GETASYNCKEYSTATE"); cpu->ax = 0; }
void USER_GETCLIENTRECT(CPU *cpu) { (void)cpu; WIN16_LOG("GETCLIENTRECT"); cpu->ax = 0; }
void USER_GETDC(CPU *cpu) { (void)cpu; WIN16_LOG("GETDC"); cpu->ax = 0; }
void USER_GETDESKTOPWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("GETDESKTOPWINDOW"); cpu->ax = 0; }
void USER_GETDLGITEM(CPU *cpu) { (void)cpu; WIN16_LOG("GETDLGITEM"); cpu->ax = 0; }
void USER_GETDLGITEMINT(CPU *cpu) { (void)cpu; WIN16_LOG("GETDLGITEMINT"); cpu->ax = 0; }
void USER_GETDLGITEMTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("GETDLGITEMTEXT"); cpu->ax = 0; }
void USER_GETFOCUS(CPU *cpu) { (void)cpu; WIN16_LOG("GETFOCUS"); cpu->ax = 0; }
void USER_GETSYSCOLOR(CPU *cpu) { (void)cpu; WIN16_LOG("GETSYSCOLOR"); cpu->ax = 0; }
void USER_GETTICKCOUNT(CPU *cpu) { (void)cpu; WIN16_LOG("GETTICKCOUNT"); cpu->ax = 0; }
void USER_GETWINDOWLONG(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINDOWLONG"); cpu->ax = 0; }
void USER_GETWINDOWRECT(CPU *cpu) { (void)cpu; WIN16_LOG("GETWINDOWRECT"); cpu->ax = 0; }
void USER_KILLTIMER(CPU *cpu) { (void)cpu; WIN16_LOG("KILLTIMER"); cpu->ax = 0; }
void USER_LOADCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("LOADCURSOR"); cpu->ax = 0; }
void USER_LOADSTRING(CPU *cpu) { (void)cpu; WIN16_LOG("LOADSTRING"); cpu->ax = 0; }
void USER_MESSAGEBEEP(CPU *cpu) { (void)cpu; WIN16_LOG("MESSAGEBEEP"); cpu->ax = 0; }
void USER_MESSAGEBOX(CPU *cpu) { (void)cpu; WIN16_LOG("MESSAGEBOX"); cpu->ax = 0; }
void USER_MOVEWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("MOVEWINDOW"); cpu->ax = 0; }
void USER_OFFSETRECT(CPU *cpu) { (void)cpu; WIN16_LOG("OFFSETRECT"); cpu->ax = 0; }
void USER_PEEKMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("PEEKMESSAGE"); cpu->ax = 0; }
void USER_POSTQUITMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("POSTQUITMESSAGE"); cpu->ax = 0; }
void USER_REALIZEPALETTE(CPU *cpu) { (void)cpu; WIN16_LOG("REALIZEPALETTE"); cpu->ax = 0; }
void USER_REDRAWWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("REDRAWWINDOW"); cpu->ax = 0; }
void USER_RELEASECAPTURE(CPU *cpu) { (void)cpu; WIN16_LOG("RELEASECAPTURE"); cpu->ax = 0; }
void USER_RELEASEDC(CPU *cpu) { (void)cpu; WIN16_LOG("RELEASEDC"); cpu->ax = 0; }
void USER_SELECTPALETTE(CPU *cpu) { (void)cpu; WIN16_LOG("SELECTPALETTE"); cpu->ax = 0; }
void USER_SENDMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("SENDMESSAGE"); cpu->ax = 0; }
void USER_SETCLASSWORD(CPU *cpu) { (void)cpu; WIN16_LOG("SETCLASSWORD"); cpu->ax = 0; }
void USER_SETCURSOR(CPU *cpu) { (void)cpu; WIN16_LOG("SETCURSOR"); cpu->ax = 0; }
void USER_SETCURSORPOS(CPU *cpu) { (void)cpu; WIN16_LOG("SETCURSORPOS"); cpu->ax = 0; }
void USER_SETDLGITEMINT(CPU *cpu) { (void)cpu; WIN16_LOG("SETDLGITEMINT"); cpu->ax = 0; }
void USER_SETDLGITEMTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("SETDLGITEMTEXT"); cpu->ax = 0; }
void USER_SETSCROLLPOS(CPU *cpu) { (void)cpu; WIN16_LOG("SETSCROLLPOS"); cpu->ax = 0; }
void USER_SETSCROLLRANGE(CPU *cpu) { (void)cpu; WIN16_LOG("SETSCROLLRANGE"); cpu->ax = 0; }
void USER_SETTIMER(CPU *cpu) { (void)cpu; WIN16_LOG("SETTIMER"); cpu->ax = 0; }
void USER_SETWINDOWLONG(CPU *cpu) { (void)cpu; WIN16_LOG("SETWINDOWLONG"); cpu->ax = 0; }
void USER_SETWINDOWTEXT(CPU *cpu) { (void)cpu; WIN16_LOG("SETWINDOWTEXT"); cpu->ax = 0; }
void USER_SHOWWINDOW(CPU *cpu) { (void)cpu; WIN16_LOG("SHOWWINDOW"); cpu->ax = 0; }
void USER_TRANSLATEMESSAGE(CPU *cpu) { (void)cpu; WIN16_LOG("TRANSLATEMESSAGE"); cpu->ax = 0; }

/* ===== WIN87EM ===== */
void WIN87EM___FPMATH(CPU *cpu) { (void)cpu; WIN16_LOG("__FPMATH"); cpu->ax = 0; }

/* ===== WING ===== */
void WING_WINGCREATEBITMAP(CPU *cpu) { (void)cpu; WIN16_LOG("WINGCREATEBITMAP"); cpu->ax = 0; }
void WING_WINGCREATEDC(CPU *cpu) { (void)cpu; WIN16_LOG("WINGCREATEDC"); cpu->ax = 0; }
void WING_WINGRECOMMENDDIBFORMAT(CPU *cpu) { (void)cpu; WIN16_LOG("WINGRECOMMENDDIBFORMAT"); cpu->ax = 0; }
void WING_WINGSTRETCHBLT(CPU *cpu) { (void)cpu; WIN16_LOG("WINGSTRETCHBLT"); cpu->ax = 0; }

