"""
gen_win16_stubs.py - Generate the Win16 runtime API header + stub bodies.

Scans CATZDLL.DLL import relocations, resolves every (module, ordinal) to a C
shim name via win16.py, and emits:

  runtime/runtime_api.h        - prototypes for dispatch + int handlers + every
                                 Win16 import shim (included by segments.h)
  runtime/win16/win16_stubs.c  - stub bodies (log-once + return ax=0) for each
                                 shim, plus int_handler / dos_int21 stubs

The stubs make the lifted code link cleanly (the El-Fish "zero undefined
symbols" milestone). Real behavior gets filled in per-API afterward, hottest
first (see analysis/xref_imports.txt for the priority order).

Run: python tools/gen_win16_stubs.py game/CATZDLL.DLL
"""
import sys
import os

import re

sys.path.insert(0, os.path.dirname(__file__))
from ne_parse import parse_ne
from win16 import get_import, module_name, get_purge

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
IMPL_C = os.path.join(ROOT, 'runtime', 'win16', 'win16_impl.c')


def implemented_names():
    """Names hand-implemented in win16_impl.c (skip generating stubs for them)."""
    if not os.path.exists(IMPL_C):
        return set()
    text = open(IMPL_C, encoding='utf-8', errors='replace').read()
    return set(re.findall(r'^void\s+([A-Z0-9_]+)\(CPU\s*\*', text, re.M))


def collect_imports(ne):
    """Return sorted unique list of Win16Import used by import relocations."""
    seen = {}
    for seg in ne.segments:
        if not seg.is_code:
            continue
        for r in seg.relocations:
            if (r.flags & 3) not in (1, 2):
                continue
            mod = module_name(ne, r.module_idx)
            imp = get_import(mod, r.ordinal)
            seen[imp.name] = imp
    return [seen[k] for k in sorted(seen)]


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'game', 'CATZDLL.DLL')
    ne = parse_ne(exe)
    imports = collect_imports(ne)

    by_mod = {}
    for imp in imports:
        by_mod.setdefault(imp.module, []).append(imp)

    # --- runtime_api.h ---
    h = []
    h.append('/* runtime_api.h - Auto-generated by gen_win16_stubs.py. Do not edit. */')
    h.append('/* Host runtime entry points referenced by the lifted CATZDLL code:  */')
    h.append('/* indirect-call dispatchers, software-interrupt handlers, and the   */')
    h.append('/* Win16 import shims (KERNEL/USER/GDI/SOSLIB03/WING/...).            */')
    h.append('#ifndef CATZ_RUNTIME_API_H')
    h.append('#define CATZ_RUNTIME_API_H')
    h.append('')
    h.append('#include "cpu.h"')
    h.append('')
    h.append('/* ---- Indirect call dispatchers (function pointers) ---- */')
    h.append('void dispatch_far(CPU *cpu, uint16_t seg, uint16_t off);')
    h.append('void dispatch_near(CPU *cpu, uint16_t seg, uint16_t off);')
    h.append('')
    h.append('/* ---- Software interrupts (rare in Win16 code; stubbed) ---- */')
    h.append('void int_handler(CPU *cpu, int int_num);')
    h.append('void dos_int21(CPU *cpu);')
    h.append('')
    h.append(f'/* ---- Win16 import shims ({len(imports)} total) ---- */')
    for mod in sorted(by_mod):
        h.append(f'/* {mod} ({len(by_mod[mod])}) */')
        for imp in by_mod[mod]:
            h.append(f'void {imp.name}(CPU *cpu);  /* @{imp.ordinal} {imp.api} */')
        h.append('')
    h.append('#endif /* CATZ_RUNTIME_API_H */')

    with open(os.path.join(ROOT, 'runtime', 'runtime_api.h'), 'w',
              encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(h) + '\n')

    # --- win16/win16_stubs.c ---
    os.makedirs(os.path.join(ROOT, 'runtime', 'win16'), exist_ok=True)
    c = []
    c.append('/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. */')
    c.append('/* Stub bodies for every Win16 import + interrupt handler, so the   */')
    c.append('/* lifted engine links. Each logs once (with -DCATZ_TRACE_WIN16) and */')
    c.append('/* returns ax=0. Replace with real behavior hottest-API-first.       */')
    c.append('#include "runtime_api.h"')
    c.append('#include <stdio.h>')
    c.append('')
    c.append('#ifdef CATZ_TRACE_WIN16')
    c.append('#define WIN16_LOG(n) do { static int _seen; if (!_seen) { _seen = 1; \\')
    c.append('    fprintf(stderr, "[win16] %s (stub)\\n", (n)); } } while (0)')
    c.append('#else')
    c.append('#define WIN16_LOG(n) ((void)0)')
    c.append('#endif')
    c.append('/* Loud warning the first time an unknown-purge stub runs: its stack')
    c.append(' * cleanup is a guess and may corrupt. Add it to PURGE in win16.py. */')
    c.append('#define WIN16_UNKNOWN(n) do { static int _w; if (!_w) { _w = 1; \\')
    c.append('    fprintf(stderr, "[win16] *** %s: unknown stack purge (guessed 0)\\n", (n)); \\')
    c.append('    } } while (0)')
    c.append('')
    c.append('void int_handler(CPU *cpu, int int_num) {')
    c.append('    (void)cpu; WIN16_LOG("int_handler");')
    c.append('    fprintf(stderr, "[int] unhandled INT 0x%02X\\n", int_num);')
    c.append('}')
    c.append('')

    impl = implemented_names()
    skipped = 0
    for mod in sorted(by_mod):
        emitted = [imp for imp in by_mod[mod] if imp.name not in impl]
        skipped += len(by_mod[mod]) - len(emitted)
        if not emitted:
            continue
        c.append(f'/* ===== {mod} ===== */')
        for imp in emitted:
            purge = get_purge(imp.module, imp.api)
            if purge is None:
                clean = f'cpu->sp += 4; WIN16_UNKNOWN("{imp.api}");'
            else:
                clean = f'cpu->sp += 4 + {purge};'
            c.append(f'void {imp.name}(CPU *cpu) {{ (void)cpu; '
                     f'WIN16_LOG("{imp.api}"); cpu->ax = 0; {clean} }}')
        c.append('')

    with open(os.path.join(ROOT, 'runtime', 'win16', 'win16_stubs.c'), 'w',
              encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(c) + '\n')

    print(f'runtime_api.h: {len(imports)} shims across {len(by_mod)} modules')
    for mod in sorted(by_mod):
        print(f'  {mod:<12s} {len(by_mod[mod])}')


if __name__ == '__main__':
    main()
