"""
gen_win16_stubs.py - Generate the Win16 runtime API header + stub bodies.

Scans CATZDLL.DLL import relocations, resolves every (module, ordinal) to a C
shim name via win16.py, and emits:

  runtime/runtime_api.h        - prototypes for dispatch + int handlers + every
                                 Win16 import shim (included by segments.h)
  runtime/win16/win16_stubs.c  - stub bodies (log-once + return ax=0) for each
                                 shim, plus int_handler / dos_int21 stubs

The stubs make the lifted code link cleanly (the El-Fish "zero undefined
symbols" milestone). Real behavior gets filled in per-API afterward, hottest
first (see analysis/xref_imports.txt for the priority order).

Run: python tools/gen_win16_stubs.py game/CATZDLL.DLL
"""
import sys
import os

import re

sys.path.insert(0, os.path.dirname(__file__))
from ne_parse import parse_ne
from win16 import get_import, module_name, get_purge

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
IMPL_FILES = [os.path.join(ROOT, 'runtime', 'win16', 'win16_impl.c'),
              os.path.join(ROOT, 'runtime', 'win16', 'win32_backend.c')]


def implemented_names():
    """Names hand-implemented in the runtime (skip generating stubs for them)."""
    names = set()
    for path in IMPL_FILES:
        if os.path.exists(path):
            text = open(path, encoding='utf-8', errors='replace').read()
            names |= set(re.findall(r'^void\s+([A-Za-z0-9_]+)\(CPU\s*\*', text, re.M))
    return names


# Modules that are other lifted recomp modules, not Win16 shims: their imports
# are cross-module calls resolved directly by the lifter, so no stub is emitted.
CROSS_MODULES = {'CATZDLL'}


def collect_imports(ne, seen):
    """Accumulate Win16Import used by import relocations into `seen` (by name)."""
    for seg in ne.segments:
        if not seg.is_code:
            continue
        for r in seg.relocations:
            if (r.flags & 3) not in (1, 2):
                continue
            mod = module_name(ne, r.module_idx)
            if mod.upper() in CROSS_MODULES:
                continue
            imp = get_import(mod, r.ordinal)
            seen[imp.name] = imp
    return seen


def main():
    # Union the import surface of every module that shares the shim layer.
    exes = sys.argv[1:] or [os.path.join(ROOT, 'game', 'CATZDLL.DLL'),
                            os.path.join(ROOT, 'game', 'CATZ.WAD')]
    seen = {}
    for exe in exes:
        if os.path.exists(exe):
            collect_imports(parse_ne(exe), seen)
    imports = [seen[k] for k in sorted(seen)]

    by_mod = {}
    for imp in imports:
        by_mod.setdefault(imp.module, []).append(imp)

    # --- runtime_api.h ---
    h = []
    h.append('/* runtime_api.h - Auto-generated by gen_win16_stubs.py. Do not edit. */')
    h.append('/* Host runtime entry points referenced by the lifted CATZDLL code:  */')
    h.append('/* indirect-call dispatchers, software-interrupt handlers, and the   */')
    h.append('/* Win16 import shims (KERNEL/USER/GDI/SOSLIB03/WING/...).            */')
    h.append('#ifndef CATZ_RUNTIME_API_H')
    h.append('#define CATZ_RUNTIME_API_H')
    h.append('')
    h.append('#include "cpu.h"')
    h.append('')
    h.append('/* ---- Indirect call dispatchers (function pointers) ---- */')
    h.append('void dispatch_far(CPU *cpu, uint16_t seg, uint16_t off);')
    h.append('void dispatch_near(CPU *cpu, uint16_t seg, uint16_t off);')
    h.append('')
    h.append('/* ---- Software interrupts (rare in Win16 code; stubbed) ---- */')
    h.append('void int_handler(CPU *cpu, int int_num);')
    h.append('void dos_int21(CPU *cpu);')
    h.append('')
    h.append(f'/* ---- Win16 import shims ({len(imports)} total) ---- */')
    for mod in sorted(by_mod):
        h.append(f'/* {mod} ({len(by_mod[mod])}) */')
        for imp in by_mod[mod]:
            h.append(f'void {imp.name}(CPU *cpu);  /* @{imp.ordinal} {imp.api} */')
        h.append('')
    h.append('#endif /* CATZ_RUNTIME_API_H */')

    with open(os.path.join(ROOT, 'runtime', 'runtime_api.h'), 'w',
              encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(h) + '\n')

    # --- win16/win16_stubs.c ---
    os.makedirs(os.path.join(ROOT, 'runtime', 'win16'), exist_ok=True)
    c = []
    c.append('/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. */')
    c.append('/* Stub bodies for every Win16 import + interrupt handler, so the   */')
    c.append('/* lifted engine links. Each logs once (with -DCATZ_TRACE_WIN16) and */')
    c.append('/* returns ax=0. Replace with real behavior hottest-API-first.       */')
    c.append('#include "runtime_api.h"')
    c.append('#include <stdio.h>')
    c.append('')
    c.append('/* Each stub records itself the first time it runs, so CATZ_STUB_HITS')
    c.append('   lists exactly which unimplemented APIs a session reaches. */')
    c.append('void catz_stub_hit(const char *n);')
    c.append('#define WIN16_LOG(n) do { static int _seen; if (!_seen) { _seen = 1; \\')
    c.append('    catz_stub_hit(n); } } while (0)')
    c.append('/* Loud warning the first time an unknown-purge stub runs: its stack')
    c.append(' * cleanup is a guess and may corrupt. Add it to PURGE in win16.py. */')
    c.append('#define WIN16_UNKNOWN(n) do { static int _w; if (!_w) { _w = 1; \\')
    c.append('    fprintf(stderr, "[win16] *** %s: unknown stack purge (guessed 0)\\n", (n)); \\')
    c.append('    } } while (0)')
    c.append('')
    c.append('void int_handler(CPU *cpu, int int_num) {')
    c.append('    (void)cpu; WIN16_LOG("int_handler");')
    c.append('    fprintf(stderr, "[int] unhandled INT 0x%02X\\n", int_num);')
    c.append('}')
    c.append('')

    impl = implemented_names()
    skipped = 0
    for mod in sorted(by_mod):
        emitted = [imp for imp in by_mod[mod] if imp.name not in impl]
        skipped += len(by_mod[mod]) - len(emitted)
        if not emitted:
            continue
        c.append(f'/* ===== {mod} ===== */')
        for imp in emitted:
            purge = get_purge(imp.module, imp.api)
            if purge is None:
                clean = f'cpu->sp += 4; WIN16_UNKNOWN("{imp.api}");'
            else:
                clean = f'cpu->sp += 4 + {purge};'
            c.append(f'void {imp.name}(CPU *cpu) {{ (void)cpu; '
                     f'WIN16_LOG("{imp.api}"); cpu->ax = 0; {clean} }}')
        c.append('')

    with open(os.path.join(ROOT, 'runtime', 'win16', 'win16_stubs.c'), 'w',
              encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(c) + '\n')

    print(f'runtime_api.h: {len(imports)} shims across {len(by_mod)} modules')
    for mod in sorted(by_mod):
        print(f'  {mod:<12s} {len(by_mod[mod])}')


if __name__ == '__main__':
    main()
